# Generated by Django 5.2 on 2025-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.CharField(max_length=100, verbose_name='job category'),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
