# Generated by Django 5.2 on 2025-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_jobposting_category_delete_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='is processed'),
        ),
    ]
