# Generated by Django 5.2 on 2025-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidate_education_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
