# Generated by Django 5.2 on 2025-05-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='availability_in_weeks',
            field=models.IntegerField(blank=True, null=True, verbose_name='availability in weeks'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='expected salary'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type_preference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='job type preference'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='experience'),
        ),
    ]
