# Generated by Django 5.2 on 2025-04-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboards', '0002_alter_jobposting_category_delete_jobcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='search query')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='category')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='accounts.candidate')),
            ],
            options={
                'verbose_name': 'Job Search History',
                'verbose_name_plural': 'Job Search Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCompletionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('resume_upload', 'Upload Resume'), ('skills_add', 'Add Skills'), ('education_add', 'Add Education'), ('experience_add', 'Add Experience'), ('profile_pic', 'Add Profile Picture'), ('contact_info', 'Complete Contact Information')], max_length=50, verbose_name='task type')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_tasks', to='accounts.candidate')),
            ],
            options={
                'verbose_name': 'Profile Completion Task',
                'verbose_name_plural': 'Profile Completion Tasks',
                'unique_together': {('candidate', 'task_type')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='accounts.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='dashboards.jobposting')),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-saved_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
